# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

language: rust

env:
  global:
    - CRATE_NAME=deoptloader

os:
  - linux
  - osx

script: >-
  if test -z "$TRAVIS_TAG"; then
    cargo test --verbose
  else
    cargo rustc --verbose --release
  fi

before_deploy:
  - strip target/release/$CRATE_NAME
  - tar -C target/release -czf $CRATE_NAME-$TRAVIS_TAG-$TRAVIS_OS_NAME.tar.gz $CRATE_NAME

deploy:
  api_key:
    secure: DEBZKHqRHNUY1AFmfIpxKH95ew0aexFr1UD04j3UWp7VQxGQp5T2ag+WosrovEOnV3xNBLuKHzW5Xiw6vwdnfjaDi67uo7mf/D07Wxav0nQfzAJcX6sgceCQAnp8MelDy3YELr4yR6ct3cmw4cCk0Dbo8rR7lTPojSIjk/lUnG86EU6wDulx/r2GGC2Du2RPZh9OjVtP+ppdQIxszmCyRgXXV77YyLrxy3K7tIwuCUaxx2SJZ3KUzeAIr2O+rp+Bl16tJ5fPlLWNjkr0fTlMGxQ8ZbDvqxUpod3O+CDsi1cchUhI/seZoGu1hjuFptITV/IedWAEWaCEMdIEFplwSxpW2xsvLWnGtZ2ojQvYoaBjBH7vZmzr7CigboXXBv1IvyZFilTasGLtHbvPiL3xHi/Z5gje/oQiy6fZ9Dl8TjBzhNoxDZ9UQaUpZqnNaeD1spGtk8urUJqzou1IUWO9hxvnAVys6XkzASlX+lHPeXqW2cObhSg4XQWWe2KK7F/yhx/s1Zvp0V2xJeK6VlhGehLUT0oo+szBIR7JTOeiaZUr3APTSAs/xKVmT9s0vLhipkNeLdcUhutHM/T8KZ2nK+ukXCSCJzgw3zXDT5y8aD3zjJfUMNua3T7WmDPLV568zP/afut8U3yf2KKyhpsSFQOwdVb4SiHhU0R9UmVlFKY=
  file: $CRATE_NAME-$TRAVIS_TAG-$TRAVIS_OS_NAME.tar.gz
  on:
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo

branches:
  only:
    - /^v\d+\.\d+\.\d+.*$/
    - master
