# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

language: rust

env:
  global:
    - CRATE_NAME=deoptloader

os:
  - linux
  - osx

script: >-
  if test -z "$TRAVIS_TAG"; then
    cargo test --verbose
  else
    cargo rustc --verbose --release -- -C lto
  fi

before_deploy:
  - strip target/release/$CRATE_NAME
  - tar -C target/release -czf $CRATE_NAME-$TRAVIS_TAG-$TRAVIS_OS_NAME.tar.gz $CRATE_NAME

deploy:
  api_key:
    secure: KdH1lyap6YMME2i6AiOVARLgfe2irxO27tlEvf6K7rabQX5pq49Dnd25hS4jNBw2eO6viM/drXVbM75XGRH1AgNDkaxZ60sO32myhLT6imiMOb85pRHC66HoPNLCoROMNH65s2JQy393bEZRlo1Q/4C8M8/7VLcPJaxJ58eL2luaN0UIxYyV73J+w6GHPWDMYLADTqoMFwYU4tZAAKcVJVIf+1Kx1OXTyEeV+YxsdC1lmITsew0dQ4DG1xDCM84yyNMmJmX3seOJqjBX65tvncuceuSE9VQBX8iTXHnGdUPw+CrTykwn8hCsCgW93+WS4xFfmLryHDLURrIbs3PLJKcvRTqG5Gx77sfMdR4qfpo8SEfSxcZIEjWiOzYzqBgXjokPeldCI5U37sSgl2ImVPnq7tV3yZwpQfKlSNVUmDeLhm/DeF6sX7ab87wZg5J6rcz76d58ME0vuVt0NGs5dcPScAGXzoq0V8l7o42E0GTPYvNGhLP0lUeTNcpGjIiGJe8NYgK6w+ghQ/0Y7YcWGSJlNy5khBdTDszH44G6Y3GuLKXTA3LK+lCC79x5DcZOGDBOyK8hDym8wlON8t+Ap/GbFIy0PEtRKC161wKlK7M0MQta0ch6SjHY+Ec/TwWNJqrN1vhMTPilMK0/Dqmm0PXdFfE3jehv6uACrHvqVCg=
  file: $CRATE_NAME-$TRAVIS_TAG-$TRAVIS_OS_NAME.tar.gz
  on:
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo

branches:
  only:
    - /^v\d+\.\d+\.\d+.*$/
    - master
