[package]
name = "deoptloader"
version = "0.1.0"
authors = ["Colin Snover <github.com@zetafleet.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
bitflags = "*"
byteorder = "*"
enum_primitive = "*"
nom = "*"
num = "*"
safemem = "*"

[[bin]]
name = "deoptloader"
path = "main.rs"
